# Generated by Django 5.2.11 on 2026-03-10 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("caption1", models.CharField(blank=True, max_length=500, null=True)),
                ("caption2", models.CharField(blank=True, max_length=500, null=True)),
                ("caption3", models.CharField(blank=True, max_length=500, null=True)),
                ("call_to_text", models.CharField(default="Shop Now", max_length=500)),
                ("call_to_url", models.CharField(default="/", max_length=500)),
                ("image", models.ImageField(upload_to="banner/")),
                (
                    "banner_type",
                    models.CharField(
                        choices=[
                            ("banner1", "banner1"),
                            ("banner2", "banner2"),
                            ("banner3", "banner3"),
                            ("banner4", "banner4"),
                            ("banner5", "banner5"),
                            ("banner6", "banner6"),
                            ("banner7", "banner7"),
                            ("banner8", "banner8"),
                        ],
                        default="Top",
                        max_length=50,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Links",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("link", models.URLField()),
            ],
            options={
                "verbose_name_plural": "Links",
            },
        ),
        migrations.CreateModel(
            name="NavigationLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=60)),
                (
                    "url",
                    models.CharField(
                        help_text="Can be a path like /about/ or a full URL",
                        max_length=200,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="FooterLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("is_footer", models.BooleanField(default=False)),
                ("section_name", models.CharField(max_length=200)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("links", models.ManyToManyField(to="core.links")),
            ],
            options={
                "verbose_name_plural": "FooterLinks",
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Ginamara", max_length=255)),
                (
                    "phone",
                    models.CharField(blank=True, default=1, max_length=20, null=True),
                ),
                (
                    "phone1",
                    models.CharField(blank=True, default=1, max_length=20, null=True),
                ),
                (
                    "phone2",
                    models.CharField(blank=True, default=1, max_length=20, null=True),
                ),
                (
                    "phone3",
                    models.CharField(blank=True, default=1, max_length=20, null=True),
                ),
                (
                    "logo",
                    models.ImageField(
                        default="default/Ginamara.png", upload_to="config/"
                    ),
                ),
                ("address", models.CharField(default="Kampala", max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("twitter", models.URLField(default="twitter.com")),
                ("facebook", models.URLField(default="facebook.com")),
                ("youtube", models.URLField(default="youtube.com")),
                ("instagram", models.URLField(default="instagram.com")),
                (
                    "favicon",
                    models.ImageField(
                        default="default/Ajoreb.png", upload_to="config/"
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                (
                    "banner1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="banner1",
                        to="core.banner",
                    ),
                ),
                (
                    "banner2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="banner2",
                        to="core.banner",
                    ),
                ),
                (
                    "banner3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="banner3",
                        to="core.banner",
                    ),
                ),
                (
                    "banner4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="banner4",
                        to="core.banner",
                    ),
                ),
                (
                    "banner5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="banner5",
                        to="core.banner",
                    ),
                ),
                (
                    "banner6",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="banner6",
                        to="core.banner",
                    ),
                ),
                (
                    "banner7",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="banner7",
                        to="core.banner",
                    ),
                ),
                (
                    "banner8",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="banner8",
                        to="core.banner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
    ]
