# Generated by Django 5.2.11 on 2026-05-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_focusarea_impactmetric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='instagram',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='linkedin',
            field=models.URLField(default='linkedin.com'),
        ),
    ]
