# Generated by Django 5.2.11 on 2026-05-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_siteconfiguration_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='youtube',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tiktok',
            field=models.URLField(default='tiktok.com'),
        ),
    ]
