# Generated by Django 5.2.11 on 2026-03-11 10:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "impact",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Provides training for 5 students'",
                        max_length=200,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Font Awesome icon class", max_length=100
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("research", "Research Report"),
                            ("toolkit", "Toolkit"),
                            ("guide", "Guide"),
                            ("training", "Training Material"),
                            ("brief", "Policy Brief"),
                            ("report", "Annual Report"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(blank=True, upload_to="resources/")),
                (
                    "external_url",
                    models.URLField(
                        blank=True, help_text="If resource is hosted externally"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, upload_to="resources/thumbnails/"),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
