# Generated by Django 5.2.11 on 2026-06-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_donationoption_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
