# Generated by Django 5.2.11 on 2026-06-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_alter_contact_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
