# Generated by Django 5.2.11 on 2026-06-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_alter_contact_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_id',
        ),
    ]
