# Generated by Django 5.2.11 on 2026-06-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0005_remove_contact_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='item',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='item_id',
        ),
    ]
