# Generated by Django 5.2.11 on 2026-05-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_annualreport_alter_country_options_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Watch Our Story', max_length=160)),
                ('subtitle', models.CharField(blank=True, help_text='Short line shown below the title', max_length=255)),
                ('embed_url', models.URLField(blank=True, help_text='YouTube or Vimeo embed URL (e.g. https://www.youtube.com/embed/xxxxx)')),
                ('video_file', models.FileField(blank=True, help_text='Upload an MP4 file (used when no embed URL is provided)', upload_to='intro_videos/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Poster image shown before the video plays', upload_to='intro_videos/thumbs/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Intro / Pitch Video',
                'verbose_name_plural': 'Intro / Pitch Videos',
            },
        ),
    ]
