# Generated by Django 5.2.11 on 2026-05-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_introvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='values',
            options={'ordering': ['order', 'title'], 'verbose_name_plural': 'Values'},
        ),
        migrations.AddField(
            model_name='values',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
