# Generated by Django 5.2.11 on 2026-06-04 16:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_values_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Why We Exist', help_text='Small pill / badge shown above the heading', max_length=150)),
                ('section_title', models.CharField(default="Ethical Leadership is the Foundation for Africa's Transformation", help_text='Main heading of the page', max_length=300)),
                ('intro_description', models.TextField(blank=True, help_text='Introductory paragraph below the main heading.')),
                ('challenge_title', models.CharField(default='The Challenge of Corruption in Uganda', help_text='Title of the challenge / statistics section', max_length=300)),
                ('challenge_body', ckeditor.fields.RichTextField(blank=True, help_text='Main body text with corruption statistics. Use the rich-text editor to format paragraphs, bold numbers, etc.')),
                ('source_label', models.CharField(blank=True, help_text="Visible text of the source link (e.g. 'Uganda Inspectorate of Government (IGG)')", max_length=500)),
                ('source_url', models.URLField(blank=True, help_text='URL the source label should link to')),
                ('closing_statement', ckeditor.fields.RichTextField(blank=True, help_text='Bold statement that appears below the horizontal rule, explaining why the organisation exists.')),
                ('cta_header', models.CharField(blank=True, default='This is what we believe.\nIf you believe it too, join us.', help_text='Heading above the CTA buttons', max_length=300)),
                ('cta_volunteer_text', models.CharField(default='Volunteer', max_length=100)),
                ('cta_volunteer_url', models.CharField(default='/volunteer/', max_length=500)),
                ('cta_partner_text', models.CharField(default='Partner With Us', max_length=100)),
                ('cta_partner_url', models.CharField(default='/partner/', max_length=500)),
                ('cta_programs_text', models.CharField(default='Read Our Work', max_length=100)),
                ('cta_programs_url', models.CharField(default='/programs/', max_length=500)),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide this content (the page will fall back to defaults).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Problem Page',
                'verbose_name_plural': 'Problem Page',
            },
        ),
    ]
