# Generated by Django 5.2.11 on 2026-06-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_problempage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualreport',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='values',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='values',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
