# Generated by Django 5.2.11 on 2026-03-11 10:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("position", models.CharField(max_length=160)),
                ("expertise", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, upload_to="board/")),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("linkedin_url", models.URLField(blank=True)),
                (
                    "member_type",
                    models.CharField(
                        choices=[
                            ("director", "Board Director"),
                            ("advisor", "Advisory Team"),
                        ],
                        default="director",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["member_type", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Founder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=160)),
                (
                    "certification",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Certified Fraud Examiner",
                        max_length=160,
                    ),
                ),
                ("bio", ckeditor.fields.RichTextField(blank=True)),
                ("photo", models.ImageField(blank=True, upload_to="founders/")),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="GovernanceStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Governance Structure",
            },
        ),
    ]
