# Generated by Django 5.2.11 on 2026-03-11 10:49

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", ckeditor.fields.RichTextField(blank=True)),
                ("event_date", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="events/")),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="SuccessStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("summary", models.TextField()),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "featured_image",
                    models.ImageField(blank=True, upload_to="success_stories/"),
                ),
                (
                    "impact_highlight",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '500 lives changed'",
                        max_length=200,
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="success_stories",
                        to="programs.program",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
