# Generated by Django 5.2.11 on 2026-04-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_alter_program_description_event_successstory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
    ]
