# Generated by Django 5.2.11 on 2026-06-06 14:44

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class, e.g., 'fas fa-shield-alt'", max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='professional_services/categories/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Professional Service Categories',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('featured_image', models.ImageField(blank=True, upload_to='professional_services/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='programs.professionalservicecategory')),
            ],
            options={
                'verbose_name_plural': 'Professional Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
